Repository UNDP-Data/rapida, pull requests merged in 2025-01, with the labels that each got.

#111 fix: add missing dependencies to pyproject.toml
  Dockerfile
  pyproject.toml
Labels: bug

#112 fix: changed user home directory to /data/home
  .azure/.env.example
  .azure/README.md
  .azure/aci-deploy.sh
  .azure/aci-deploy.yaml
  .env.example
  Dockerfile
  README.md
  catalog.json
  create_user.sh
  docker-compose.yaml
  entrypoint.sh
  jupyterhub_config.py
Labels: bug

#113 fix: separate home and data folder in the container.
  Dockerfile
  README.md
  create_user.sh
  jupyterhub_config.py
Labels: bug

#118 fix: delete duplicated codes from cli.py
  cbsurge/cli.py
Labels: bug

#128 fix: add vim to docker
  Dockerfile
  Makefile
  docker-compose.yaml
Labels: enhancement

#130 feat: add folium and matplotlib to dependencies
  pyproject.toml
Labels: enhancement

#132 Create LICENSE
  LICENSE
Labels: documentation

#133 feat: implement download from azure
  cbsurge/exposure/population/__init__.py
  cbsurge/exposure/population/worldpop.py
  tests/cbsurge/test_cli.py
Labels: bug, enhancement

#134 fix: add ipywidgets to pyproject.toml
  pyproject.toml
Labels: enhancement

#136 fix: fixed get_blob_container_client to get container client directly
  cbsurge/session.py
Labels: bug

#137 fix: added description for population sync and aggregatre command
  cbsurge/exposure/population/__init__.py
Labels: bug

#138 feat: aggregate total population
  cbsurge/exposure/population/constants.py
  cbsurge/exposure/population/worldpop.py
Labels: enhancement
